#!/bin/bash

: ${RESTIC_PRUNE_DOW:=0}
: ${RESTIC_BIN:=/usr/libexec/restic/restic}
: ${RESTIC_CACHE_DIR:=/var/cache/restic}
: ${INFLUXDB_URL:=}
: ${INFLUXDB_TOKEN_FILE:=}
: ${INFLUXDB_ORG:=}
: ${INFLUXDB_BUCKET:=}
: ${METRIC_NAME:=restic_backup}
: ${HOSTNAME_VALUE:=$(hostname)}
: ${DEBUG:=0}
: ${RESTIC_LOCK_FILE:=/run/restic/backup.lock}

exec 200>"$RESTIC_LOCK_FILE" || exit 1
flock 200 || exit 1

# Ensure INFLUXDB_URL doesn't have a trailing slash
INFLUXDB_URL="${INFLUXDB_URL%/}"


export RESTIC_CACHE_DIR

for required in BACKUP_DIR RESTIC_REPOSITORY; do
	if [[ -z ${!required} ]]; then
		echo "ERROR: $required is undefined" >&2
		exit 1
	fi
done

(
set -e

echo "* Starting backup of $BACKUP_DIR to $RESTIC_REPOSITORY"

if [[ -n "$INFLUXDB_URL" && -n "$INFLUXDB_ORG" && -n "$INFLUXDB_BUCKET" && -n "$INFLUXDB_TOKEN_FILE" ]]; then
	
	format_for_influx() {
		local input="$1"
		echo "$input" | sed 's/ /\\ /g' | sed 's/,/\\,/g' | sed 's/=/\\=/g'
	}

	# Check for dependencies
	for dep in curl jq; do
		if ! command -v $dep &> /dev/null; then
			echo "ERROR: $dep is not installed" >&2
			exit 1
		fi
	done

	if [[ -f "$INFLUXDB_TOKEN_FILE" ]]; then
		INFLUXDB_TOKEN=$(cat "$INFLUXDB_TOKEN_FILE")
	else
		echo "ERROR: INFLUXDB_TOKEN_FILE '$INFLUXDB_TOKEN_FILE' does not exist or is not readable" >&2
		exit 1
	fi

	echo "* Logging to InfluxDB at $INFLUXDB_URL"

	# Temporary files to store the last status and summary
	TEMP_LAST_STATUS=$(mktemp)
	TEMP_SUMMARY=$(mktemp)

	trap cleanup EXIT

	cleanup() {
		if [[ "$DEBUG" -eq 1 ]]; then
			echo "Cleaning temp files"
		fi
		rm -f "$TEMP_LAST_STATUS" "$TEMP_SUMMARY"
	}

	# Process the backup output in real-time
	while IFS= read -r line; do
		case "$line" in
			*\"message_type\":\"status\"*)
				echo "$line" > "$TEMP_LAST_STATUS"
				;;
			*\"message_type\":\"summary\"*)
				echo "$line" > "$TEMP_SUMMARY"
				break
				;;
		esac
	done < <($RESTIC_BIN $RESTIC_COMMON_ARGS backup $RESTIC_BACKUP_ARGS $BACKUP_DIR --json)

	# Extract the error count from the last status message
	LAST_STATUS=$(cat "$TEMP_LAST_STATUS")
	
	# `// 0` means setting to 0 when the field is not present
	ERROR_COUNT=$(echo "$LAST_STATUS" | jq -r '.error_count // 0')

	SUMMARY=$(cat "$TEMP_SUMMARY")

	if [[ "$DEBUG" -eq 1 ]]; then
		echo "Last status: $LAST_STATUS"
		echo "Error count: $ERROR_COUNT"
		echo "Summary: $SUMMARY"
	fi
	
	FORMATTED_BACKUP_DIR=$(format_for_influx "$BACKUP_DIR")
	FORMATTED_REPO=$(format_for_influx "$RESTIC_REPOSITORY")

	declare -A metrics
	keys=(
		"files_new"
		"files_changed"
		"files_unmodified"
		"dirs_new"
		"dirs_changed"
		"dirs_unmodified"
		"data_blobs"
		"tree_blobs"
		"data_added"
		"total_files_processed"
		"total_bytes_processed"
		"total_duration"
		"snapshot_id"
		"error_count"
	)

	for key in "${keys[@]}"; do
		if [[ "$key" == "error_count" ]]; then
			metrics["$key"]="$ERROR_COUNT"
		else
			metrics["$key"]=$(echo "$SUMMARY" | jq ".$key")
		fi
	done

	DATA="$METRIC_NAME,host=$HOSTNAME_VALUE,backup_dir=$FORMATTED_BACKUP_DIR,repository=$FORMATTED_REPO "
	for key in "${keys[@]}"; do
		DATA+="$key=${metrics[$key]},"
	done
	DATA=${DATA%,}  # Remove the trailing comma

	if [[ $DEBUG -eq 1 ]]; then
		echo "Payload: $DATA"
	fi

	curl -sS "$INFLUXDB_URL/api/v2/write?org=$INFLUXDB_ORG&bucket=$INFLUXDB_BUCKET" \
		-H "Authorization: Token $INFLUXDB_TOKEN" \
		--data-binary "$DATA"

else
	$RESTIC_BIN $RESTIC_COMMON_ARGS backup $RESTIC_BACKUP_ARGS $BACKUP_DIR
fi

today=$(date +%w)
if (( today == RESTIC_PRUNE_DOW )); then
	echo "* Pruning old backups from $BACKUP_DIR in $RESTIC_REPOSITORY"
	$RESTIC_BIN $RESTIC_COMMON_ARGS \
		forget --prune $RESTIC_FORGET_ARGS
fi
)

retcode=$?

echo "* Ensuring that repository $RESTIC_REPOSITORY is unlocked"
$RESTIC_BIN $RESTIC_COMMON_ARGS \
	unlock

exit $retcode
